import { RuleDefinition } from "@/lib/scanner/types";

export const RULES: RuleDefinition[] = [
  {
    id: "robots_accessible",
    rootCause: "crawl_access",
    pillar: "FINDABILITY",
    component: "Crawl Controls",
    weight: 4,
    severity: "medium",
    check: "fetch robots.txt",
    pass_condition: "robots.txt is reachable",
    message: "robots.txt could not be read",
    explanation: "The site does not expose a readable robots.txt file at the root.",
    impact: "This makes crawl guidance less clear and can weaken discovery signals for automated systems.",
    whatToDo: "Publish a robots.txt file for the site.",
    howToDoIt: [
      "Ask your web developer to create a robots.txt file at your main domain root, like example.com/robots.txt.",
      "Make sure the file opens normally in a browser and does not return an error.",
      "Add a sitemap line in that file if your site has a sitemap.",
    ],
    assignments: [
      {
        role: "Developer",
        responsibility: "Create the robots.txt file and make sure it loads correctly at the site root.",
      },
    ],
  },
  {
    id: "crawlability_allowed",
    rootCause: "crawl_access",
    pillar: "FINDABILITY",
    component: "Crawl Controls",
    weight: 6,
    severity: "high",
    check: "check robots allow rules",
    pass_condition: "page path is allowed for general crawlers",
    message: "This page is blocked from crawling",
    explanation: "The current robots rules prevent this page from being fetched by crawlers.",
    impact: "If the page cannot be crawled, its content is much harder to read, attribute, and reference reliably.",
    whatToDo: "Remove the crawl block if this page should be found.",
    howToDoIt: [
      "Ask your web developer to check the robots.txt rules that match this page or section.",
      "If this page should appear in search and AI systems, remove the rule that blocks it.",
      "Test the page again after the rule is changed.",
    ],
    assignments: [
      {
        role: "Developer",
        responsibility: "Review the robots rules and remove the crawl block if this page should be discoverable.",
      },
    ],
  },
  {
    id: "meta_noindex_present",
    rootCause: "indexing_control",
    pillar: "FINDABILITY",
    component: "Indexability",
    weight: 7,
    severity: "high",
    check: "detect noindex directives",
    pass_condition: "no noindex in meta robots or x-robots-tag",
    message: "Page is marked noindex",
    explanation: "The page includes a directive telling search systems not to index it.",
    impact: "This sharply reduces visibility and makes the page a weak candidate for discovery or citation.",
    whatToDo: "Remove the instruction that hides this page from search.",
    howToDoIt: [
      "Ask your web developer to check both the page code and server headers for a noindex instruction.",
      "Remove that instruction if this page should be found in search results.",
      "Keep it only if you intentionally want the page hidden.",
    ],
    assignments: [
      {
        role: "Developer",
        responsibility: "Remove the noindex instruction from the page code or server headers if the page should appear in search.",
      },
    ],
  },
  {
    id: "snippet_eligibility",
    rootCause: "preview_control",
    pillar: "FINDABILITY",
    component: "Preview Signals",
    weight: 4,
    severity: "medium",
    check: "detect snippet-limiting directives",
    pass_condition: "page allows normal snippets and previews",
    message: "Page limits or blocks search previews",
    explanation: "The page restricts how much preview text can appear in search or AI summaries.",
    impact: "Limited previews make it harder for systems to show useful context about the page.",
    whatToDo: "Allow normal page previews.",
    howToDoIt: [
      "Ask your web developer to remove settings in the page code or headers that block or shorten previews.",
      "Let search systems show a normal short preview if you want the page to be easier to understand.",
      "Keep strict preview limits only when there is a clear business reason.",
    ],
    assignments: [
      {
        role: "Developer",
        responsibility: "Remove the setting that blocks or limits search previews if normal previews are desired.",
      },
    ],
  },
  {
    id: "sitemap_present",
    rootCause: "discovery_support",
    pillar: "FINDABILITY",
    component: "Discovery",
    weight: 2,
    severity: "low",
    check: "look for sitemap hints",
    pass_condition: "robots.txt or the site exposes a sitemap",
    message: "No sitemap signal was found",
    explanation: "The site does not clearly point crawlers to a sitemap.",
    impact: "Without a sitemap, important pages can be slower to discover and organize.",
    whatToDo: "Publish a sitemap and point to it clearly.",
    howToDoIt: [
      "Ask your web developer to create a sitemap file, usually at example.com/sitemap.xml.",
      "Add the sitemap link inside robots.txt so machines can find it quickly.",
      "Keep the sitemap updated when important pages are added or removed.",
    ],
    assignments: [
      {
        role: "Developer",
        responsibility: "Publish the sitemap and link to it from robots.txt.",
      },
    ],
  },
  {
    id: "canonical_present",
    rootCause: "url_definition",
    pillar: "FINDABILITY",
    component: "Canonicalization",
    weight: 2,
    severity: "low",
    check: "read canonical tag",
    pass_condition: "page declares a canonical URL",
    message: "Canonical URL is missing",
    explanation: "The page does not identify its preferred URL version.",
    impact: "This can weaken URL clarity and make attribution less consistent across duplicate paths.",
    whatToDo: "Set one preferred URL for this page.",
    howToDoIt: [
      "Ask your web developer to add a canonical link in the page head.",
      "Point it to the main public version of this page, not a duplicate or tracking URL.",
      "Use that same preferred URL across any duplicate versions of the page.",
    ],
    assignments: [
      {
        role: "Developer",
        responsibility: "Add the preferred page URL in the page head and keep it consistent across duplicate URLs.",
      },
    ],
  },
  {
    id: "h1_present",
    rootCause: "article_structure",
    pillar: "INTERPRETATION",
    component: "Structure",
    weight: 5,
    severity: "medium",
    check: "count H1 tags",
    pass_condition: "page has one clear H1",
    message: "One main heading is not clearly defined",
    explanation: "The page does not define one clear top heading for the primary content in a consistent way.",
    impact: "A weak primary heading makes the page harder to interpret quickly and summarize correctly.",
    whatToDo: "Add one clear main headline.",
    howToDoIt: [
      "Place one main headline near the top of the page content.",
      "Make the headline say exactly what the page is about in simple words.",
      "Do not use multiple main headlines that compete with each other.",
    ],
    assignments: [
      {
        role: "Editorial / Content",
        responsibility: "Write one clear main headline that plainly matches the page topic.",
      },
    ],
  },
  {
    id: "heading_hierarchy",
    rootCause: "article_structure",
    pillar: "INTERPRETATION",
    component: "Structure",
    weight: 4,
    severity: "low",
    check: "count heading coverage",
    pass_condition: "content uses multiple headings to break up sections",
    message: "Article sections are not clearly defined",
    explanation: "The page does not define section headings clearly enough for the article structure to read consistently.",
    impact: "Weak section structure makes the content harder for both people and machines to scan.",
    whatToDo: "Break the page into clear sections.",
    howToDoIt: [
      "Add subheadings throughout the page so each topic has its own section.",
      "Use short section titles that match what the text below is about.",
      "Place a new heading whenever the topic changes.",
    ],
    assignments: [
      {
        role: "Editorial / Content",
        responsibility: "Break the page into clearer sections and add simple subheadings where topics change.",
      },
    ],
  },
  {
    id: "paragraph_structure",
    rootCause: "article_structure",
    pillar: "INTERPRETATION",
    component: "Readability",
    weight: 4,
    severity: "medium",
    check: "count and size paragraphs",
    pass_condition: "page has readable paragraph structure",
    message: "Paragraph structure is not clearly defined",
    explanation: "The page does not break the body text into clean paragraph groups consistently enough for easy extraction.",
    impact: "Dense text is harder to parse, summarize, and extract into clear answer-ready chunks.",
    whatToDo: "Rewrite long text into shorter paragraphs.",
    howToDoIt: [
      "Split dense text blocks into smaller paragraphs on the page.",
      "Keep each paragraph focused on one idea or answer.",
      "Use spacing so the content is easier to scan on desktop and mobile.",
    ],
    assignments: [
      {
        role: "Editorial / Content",
        responsibility: "Rewrite dense text into shorter paragraphs with one idea per paragraph.",
      },
    ],
  },
  {
    id: "extractable_main_content",
    rootCause: "article_structure",
    pillar: "INTERPRETATION",
    component: "Readability",
    weight: 5,
    severity: "high",
    check: "detect article or main content containers",
    pass_condition: "main content is easy to isolate",
    message: "Main content is not clearly separated from the page layout",
    explanation: "The page does not clearly separate the article body from navigation, promos, or surrounding layout.",
    impact: "This makes it harder for systems to isolate the real content and attribute it correctly.",
    whatToDo: "Make the main content area more obvious.",
    howToDoIt: [
      "Ask your web developer to keep the article or page body inside one clear main content area in the code.",
      "Move menus, sidebars, and promotional blocks outside that main content area.",
      "Make sure the most important text appears in the primary reading section of the page.",
    ],
    assignments: [
      {
        role: "Editorial / Content",
        responsibility: "Keep the main article or page body focused on the core content instead of promos or repeated navigation text.",
      },
      {
        role: "Developer",
        responsibility: "Place the core content inside one clear main content area in the page code.",
      },
    ],
  },
  {
    id: "author_byline",
    rootCause: "author_identity",
    pillar: "INTERPRETATION",
    component: "Attribution",
    weight: 3,
    severity: "medium",
    check: "detect author information",
    pass_condition: "page shows an author or publisher byline",
    message: "Author information is not clearly defined",
    explanation: "The page does not clearly show who wrote the content.",
    impact: "Machines rely on clear author information to attribute content to a person. Without it, attribution can be weaker or inconsistent across platforms.",
    whatToDo: "Show who wrote the content.",
    howToDoIt: [
      "Add the writer name near the headline or near the start of the article.",
      "Link that name to an author bio page if you have one.",
      "Use the same author name on the page, on profile pages, and in your site code.",
    ],
    assignments: [
      {
        role: "Editorial / Content",
        responsibility: "Show the author name clearly near the headline and keep it consistent across the site.",
      },
      {
        role: "Developer",
        responsibility: "Link the author to a profile page and expose matching author details in the page code.",
      },
    ],
  },
  {
    id: "publication_date",
    rootCause: "article_context",
    pillar: "INTERPRETATION",
    component: "Freshness",
    weight: 2,
    severity: "low",
    check: "detect publication or modified date",
    pass_condition: "page includes a publication or update date",
    message: "Publication date is not clearly defined",
    explanation: "The page does not clearly show when the content was published or updated.",
    impact: "Machines use date information to place content in time. Without it, freshness and context are harder to interpret.",
    whatToDo: "Show the publish or update date.",
    howToDoIt: [
      "Place the date near the headline or author line where readers can easily see it.",
      "Use a real publish date or last updated date, not a generic label.",
      "Keep the visible date accurate when the page changes.",
    ],
    assignments: [
      {
        role: "Editorial / Content",
        responsibility: "Add a real publish or update date near the headline or author line.",
      },
    ],
  },
  {
    id: "content_depth",
    rootCause: "article_structure",
    pillar: "INTERPRETATION",
    component: "Depth",
    weight: 2,
    severity: "medium",
    check: "estimate content depth",
    pass_condition: "page has substantial text content",
    message: "Content depth may be limited for machine extraction",
    explanation: "The scan found less extractable body text than expected.",
    impact: "When extractable body text is limited, machines have less context to understand the topic and summarize it clearly.",
    whatToDo: "Check whether the page needs more extractable body text or clearer article structure.",
    howToDoIt: [
      "Add more useful body text if the page is meant to explain a topic in depth.",
      "Keep the main text inside a clear article or main content area.",
      "Use headings and paragraphs so the body text is easier to extract.",
    ],
    assignments: [
      {
        role: "Editorial / Content",
        responsibility: "Decide whether the page should include more body text, examples, or supporting detail.",
      },
      {
        role: "Developer",
        responsibility: "Make sure the main article text is exposed in a clear, extractable content area.",
      },
    ],
  },
  {
    id: "publisher_identity",
    rootCause: "publisher_identity",
    pillar: "ATTRIBUTION",
    component: "Identity",
    weight: 8,
    severity: "high",
    check: "detect organization or site identity signals",
    pass_condition: "site clearly identifies its publisher",
    message: "Publisher identity is not clearly defined",
    explanation: "The page does not define the publisher consistently enough for humans and machines to connect the content to one source.",
    impact: "Machines rely on consistent identity details to attribute content to a source. Without this, attribution is weaker and less consistent across platforms.",
    visibleLayer: "Publisher details like name, logo, and About-page links are not consistently shown on the page.",
    machineLayer: "Article markup and site code do not consistently define the same publisher record and official profile links.",
    whatToDo: "Define publisher details clearly on the page and in the site code.",
    howToDoIt: [
      "Show your business or publication name clearly on the page or in the site header or footer.",
      "Add your logo and link to an About page or publisher page that explains who you are.",
      "Ask your web developer to add machine-readable publisher details in the code, including your name, logo, and official profile links.",
    ],
    assignments: [
      {
        role: "Brand / Marketing",
        responsibility: "Decide which publisher name, logo, and official profile links should represent the brand.",
      },
      {
        role: "Developer",
        responsibility: "Add those publisher details to the page code and connect them clearly to the article page.",
      },
    ],
  },
  {
    id: "author_presence",
    rootCause: "author_identity",
    pillar: "ATTRIBUTION",
    component: "Identity",
    weight: 5,
    severity: "medium",
    check: "detect author pages or person schema",
    pass_condition: "author identity is linked or described",
    message: "Author identity is not clearly defined",
    explanation: "The page does not consistently connect the article to one clearly defined author.",
    impact: "Machines rely on consistent author information to attribute content to a person. Without it, authorship can be weaker or inconsistent across platforms.",
    visibleLayer: "Author information like name, bio, or profile links is not consistently shown with the article.",
    machineLayer: "Article markup and site code do not consistently define the same author details.",
    whatToDo: "Make the author easier to recognize and verify.",
    howToDoIt: [
      "Show the author name clearly on the page, close to the headline or intro.",
      "Link the name to an author bio or profile page that explains who that person is.",
      "Ask your web developer to add machine-readable author details in the code so systems can connect the person to the content.",
    ],
    assignments: [
      {
        role: "Editorial / Content",
        responsibility: "Make sure the author name and bio details are clearly shown on the page.",
      },
      {
        role: "Developer",
        responsibility: "Connect the author page details to machine-readable author markup in the code.",
      },
    ],
  },
  {
    id: "social_profile_links",
    rootCause: "publisher_identity",
    pillar: "ATTRIBUTION",
    component: "Profiles",
    weight: 5,
    severity: "medium",
    check: "find social or profile links",
    pass_condition: "site links to at least one social or profile page",
    message: "Cross-platform identity is weak or disconnected",
    explanation: "The page does not connect the publisher or author clearly enough to official profiles across the web.",
    impact: "Machines use profile links to connect content to a brand or person across platforms. Without them, identity matching is less reliable.",
    visibleLayer: "Official profile links are limited or hard to find in visible page content.",
    machineLayer: "Official profile links are not consistently defined in the site code.",
    whatToDo: "Link to your official profiles.",
    howToDoIt: [
      "Add links on the page or footer to official profiles for your brand or author, such as LinkedIn, YouTube, or X.",
      "Use the same brand or author name across those profiles.",
      "Only link to accounts you control and actively use.",
    ],
    assignments: [
      {
        role: "Brand / Marketing",
        responsibility: "Choose the official public profiles that best represent the brand or author and keep them current.",
      },
    ],
  },
  {
    id: "sameas_schema",
    rootCause: "publisher_identity",
    pillar: "ATTRIBUTION",
    component: "Profiles",
    weight: 4,
    severity: "medium",
    check: "inspect sameAs schema",
    pass_condition: "structured data includes sameAs links",
    message: "Cross-platform identity is weak or disconnected",
    explanation: "The site code does not connect the publisher or author clearly enough to official profiles across the web.",
    impact: "Machines use profile links in site code to connect content to a known source. Without them, attribution can be weaker across platforms.",
    visibleLayer: "Visible profile links may exist, but they do not create a strong cross-platform identity by themselves.",
    machineLayer: "Official profile links are not consistently defined in the site code.",
    whatToDo: "Add machine-readable links to your official profiles.",
    howToDoIt: [
      "Ask your web developer to place official profile links in the page code, not just in visible page text.",
      "Use links to real company pages, author pages, or official social profiles you control.",
      "Keep those links consistent across your site and profile pages.",
    ],
    assignments: [
      {
        role: "Brand / Marketing",
        responsibility: "Confirm which official profiles should be linked for the brand or author.",
      },
      {
        role: "Developer",
        responsibility: "Add those official profile links into the page code so machines can connect them reliably.",
      },
    ],
  },
  {
    id: "external_platform_mentions",
    rootCause: "external_context",
    pillar: "ATTRIBUTION",
    component: "References",
    weight: 3,
    severity: "low",
    check: "count outbound links to external platforms",
    pass_condition: "content references trusted external destinations",
    message: "External references are limited",
    explanation: "The page includes few links to outside sources, profiles, or related public pages.",
    impact: "Machines use outside references to place content in a broader context. Without them, source context is thinner.",
    whatToDo: "Add useful outside links that support trust and context.",
    howToDoIt: [
      "Link to source pages, author pages, or publisher pages when they help explain the content.",
      "Add outside links where they genuinely help a reader verify the topic or identity.",
      "Avoid adding links only for promotion with no clear value.",
    ],
    assignments: [
      {
        role: "Brand / Marketing",
        responsibility: "Choose the outside profile or brand pages that best support identity and trust.",
      },
      {
        role: "Editorial / Content",
        responsibility: "Add those supporting links where they help readers understand the source or brand.",
      },
    ],
  },
  {
    id: "schema_presence",
    rootCause: "page_code_definition",
    pillar: "DELIVERY",
    component: "Structured Data",
    weight: 8,
    severity: "high",
    check: "detect JSON-LD schema",
    pass_condition: "page includes structured data",
    message: "Key page details are not consistently defined",
    explanation: "The site code does not define core page details clearly enough for machines to understand the article consistently.",
    impact: "Machines use site code to understand page type, attribution, and content meaning. Without it, interpretation is less reliable.",
    visibleLayer: "Page details may be visible to readers, but they are not consistently mirrored in the site code.",
    machineLayer: "The site code does not clearly define page type, title, author, publisher, or date.",
    whatToDo: "Add machine-readable page details in the code.",
    howToDoIt: [
      "Ask your web developer to add structured markup in the page code that describes the page.",
      "Include the page title, author, publisher, and date if they are available.",
      "Make sure those details match what people can see on the page.",
    ],
    assignments: [
      {
        role: "Developer",
        responsibility: "Add machine-readable page details in the code for the page title, author, publisher, and date.",
      },
    ],
  },
  {
    id: "schema_completeness",
    rootCause: "page_code_definition",
    pillar: "DELIVERY",
    component: "Structured Data",
    weight: 6,
    severity: "medium",
    check: "inspect schema coverage",
    pass_condition: "schema covers the page type and key fields",
    message: "Key page details are not consistently defined",
    explanation: "The site code includes some page details, but key article, author, publisher, or profile-link fields are not fully defined.",
    impact: "Machines rely on complete page details in the site code to understand content and attribution. Incomplete definitions weaken that understanding.",
    visibleLayer: "Readers may see page details on the page, but they are not fully matched in the site code.",
    machineLayer: "Article markup is present, but key page details are missing or incomplete in the site code.",
    whatToDo: "Fill in the missing machine-readable details.",
    howToDoIt: [
      "Ask your web developer to complete the page markup with the title, author, publisher, and date.",
      "Add official profile links for the brand or author where appropriate.",
      "Check that the code and the visible page show the same details.",
    ],
    assignments: [
      {
        role: "Brand / Marketing",
        responsibility: "Confirm the correct brand and profile details that should appear in the page markup.",
      },
      {
        role: "Developer",
        responsibility: "Complete the missing machine-readable page details and make sure they match the visible page content.",
      },
    ],
  },
  {
    id: "mobile_viewport",
    rootCause: "mobile_foundation",
    pillar: "DELIVERY",
    component: "Mobile Usability",
    weight: 3,
    severity: "medium",
    check: "look for viewport meta tag",
    pass_condition: "page declares a mobile viewport",
    message: "Mobile viewport tag is missing",
    explanation: "The page does not declare a responsive viewport for mobile devices.",
    impact: "This weakens mobile usability and can reduce the quality of the page experience.",
    whatToDo: "Make sure the page works well on mobile.",
    howToDoIt: [
      "Ask your web developer to add mobile page settings in the page head.",
      "Test the page on a phone-sized screen, not just desktop.",
      "Make sure text, images, and layout resize properly on small screens.",
    ],
    assignments: [
      {
        role: "Developer",
        responsibility: "Add the mobile page settings and confirm the layout resizes properly on phone screens.",
      },
    ],
  },
  {
    id: "basic_performance",
    rootCause: "delivery_foundation",
    pillar: "DELIVERY",
    component: "Responsiveness",
    weight: 4,
    severity: "medium",
    check: "measure response time",
    pass_condition: "initial response time is reasonably fast",
    message: "Page delivery is slowing machine access",
    explanation: "The page takes too long to return its first response.",
    impact: "Slow delivery can reduce crawl efficiency and weaken the overall content experience.",
    visibleLayer: "Readers may still reach the page, but delivery starts later than expected.",
    machineLayer: "Slower response time makes it harder for automated systems to fetch the page efficiently.",
    whatToDo: "Speed up the page response.",
    howToDoIt: [
      "Ask your web developer to check why the page is slow to start loading.",
      "Reduce heavy work that happens before the page content appears.",
      "Review caching, hosting, or page generation settings if the delay continues.",
    ],
    assignments: [
      {
        role: "Developer",
        responsibility: "Investigate the slow page response and reduce the delay before content starts loading.",
      },
    ],
  },
  {
    id: "html_structure",
    rootCause: "page_code_definition",
    pillar: "INTERPRETATION",
    component: "Markup Quality",
    weight: 2,
    severity: "low",
    check: "inspect basic HTML structure",
    pass_condition: "page has title, description, and html lang",
    message: "Page metadata is not consistently defined",
    explanation: "The page title, description, or language is missing or not clearly defined in the site code.",
    impact: "Machines use page metadata to interpret the topic, summarize the page, and understand language context. Missing metadata weakens interpretation.",
    visibleLayer: "Readers may understand the page, but the topic and language are not fully reinforced by page metadata.",
    machineLayer: "The site code is missing or weakening the page title, meta description, or language definition.",
    whatToDo: "Define the page title, description, and language clearly.",
    howToDoIt: [
      "Add a clear page title that matches the main topic.",
      "Add a useful meta description that summarizes the page content.",
      "Define the correct page language in the site code.",
    ],
    assignments: [
      {
        role: "Developer",
        responsibility: "Define the page title, description, and language settings in the site code.",
      },
    ],
  },
  {
    id: "redirect_health",
    rootCause: "delivery_foundation",
    pillar: "DELIVERY",
    component: "Delivery",
    weight: 2,
    severity: "low",
    check: "inspect redirect and status behavior",
    pass_condition: "page resolves cleanly with a successful status",
    message: "The page resolves through errors or excessive redirects",
    explanation: "The page does not resolve cleanly and may depend on redirects or error responses.",
    impact: "Messy delivery paths can waste crawl budget and make the page less dependable to fetch.",
    whatToDo: "Make the page open directly and cleanly.",
    howToDoIt: [
      "Ask your web developer to remove extra redirects before the final page loads.",
      "Make sure the final public URL returns a normal successful response.",
      "Update internal links so they go straight to the final page URL.",
    ],
    assignments: [
      {
        role: "Developer",
        responsibility: "Reduce unnecessary redirects and make sure internal links go straight to the final page URL.",
      },
    ],
  },
];
